controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 1.0 # max time between command messages before the vehicle should stop
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    kinematics:
        base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
        wheels_radius: 0.3
        sum_of_robot_center_projection_on_X_Y_axis: 1.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true

mecanum_controller:
  ros__parameters:
    reference_timeout: 0.9
    
    front_left_wheel_command_joint_name: home_base_front_left_mecanum_left_wheel_joint
    front_right_wheel_command_joint_name: home_base_front_right_mecanum_right_wheel_joint
    rear_left_wheel_command_joint_name: home_base_rear_left_mecanum_right_wheel_joint
    rear_right_wheel_command_joint_name: home_base_rear_right_mecanum_left_wheel_joint

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.5
      sum_of_robot_center_projection_on_X_Y_axis: 1.0

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    
    # Frame configuration
    odom_frame_id: odom
    base_frame_id: home_base_base_link
    
    # Publishing
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    enable_odom_tf: true

